#ENC[AES256_GCM,data:XWiRwUhEaO5Vf8QUdAGBCgEJqbh8FvSgg7zRx2ZZsI+ug2EEVSa+,iv:k4zQ55oi5enit8nQKFI3kSgK84Lkiyc88YcfuUtFQxk=,tag:n0etLypl0BKPmT3T7UR6pA==,type:comment]
#
#ENC[AES256_GCM,data:05DRYuM35OzuQ0PuT/YJgYcWoivzsO8g9J/1ARaD+7u8jwGurwE=,iv:C3jy9qULuW4ICTgW1PrAtNnpqkN7sBKebsdT7cm9Gx0=,tag:JZSV2qPLS3rg2O0piF90Wg==,type:comment]
#ENC[AES256_GCM,data:+V3earnGEHSMTFYuuhdwrXwCC6sRdIhlixPO8i7a5A4Ms7kIY2BtKOXc/6ZGRIVP30WKC9CtaR2GiC0UT2DtT9dJuoV2,iv:xzER6F6FRUvR+5a6rSb0jK3yNq+dgi0LujzmyrIUIlw=,tag:Wj7ctm9nbEJ6aQusmTVOqg==,type:comment]
#ENC[AES256_GCM,data:QUEb+FLLdpahfrMHixK4UM8OeQ9XvF/ECI51g0uUEnaLg/4vB7AcoTOxBl/yAm/LSA==,iv:e7Q5g/LT5je7UiBVkCYZ+jUS8gA+P44wbmT7c2omeCU=,tag:Lx72N73o+giwu/FbQpcJLw==,type:comment]
#ENC[AES256_GCM,data:ZavdbN5E9Ri4hD9x4mEpYqgYg1cPrSehSlT5YXKNxOlg9adArhW/vU1wRw==,iv:SLDV/jXj1N5ai88+g89Pn08VBHpKAs3ryPj6t3elZWA=,tag:Za6i5XSvvTxf9biCEBo99g==,type:comment]
#ENC[AES256_GCM,data:0muQpnjsJo0azpn76ppcWsSeFjF2dfmykWRmXRngk19nnjIGEFLoQWp9zNHzo0ofLZBaokCaDEo=,iv:sgQon+CPW/h02ga4FXdOBN6i2J7UFifrY8Z0NEZPduY=,tag:a9IYF7Yj0RxW1ArVGDgzJQ==,type:comment]
#
#ENC[AES256_GCM,data:YtQfy9Yjyls0fQbZmwX2t14D6Ud0VHNRC7DKbE5drAsmPlAAVxRgI1BYnlzzeEMGWZZWtzA8/uKV5Ek4,iv:Y1aidXvCgPfHpn7dQ/WmVuRraewnEK3Z+n/Khn2RpD0=,tag:AhoeKN2FOYb8dMfjVN6waw==,type:comment]
#ENC[AES256_GCM,data:PXbZ7rjL2XN4WbDra6Xn+BZFPBGJhrWIxH8djR2jjVZh1Ncn95xYaX3LwqHy5E3Byhx9GHAfwSfOdhVFa105Vg1Qkg7/wGgeIgs=,iv:yEn/hz+duC/fsbYYn1LZEhFO+gZcfx+rPo9ICrB0Ho4=,tag:7/VhFd+AaWPJ2DBDvolYRQ==,type:comment]
#
#ENC[AES256_GCM,data:Rx0s2UQgRHjsL+QnSLa+rl0RtDQl5TGHWkVhaYpFKESLuxt31azxMffXunaP8/YGe9s+1YCzX3lPTerxLWrDVvE=,iv:N3lrNAVJ4ZTZ4HnLPqyFlZ3fYUqxTWqrHPbrrCcUa+U=,tag:0OKFocExAAdjX/eu42fDEQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:zU8=,iv:H3/WOYuOB41myCsbN6EtMy2DYaZiAn9/E0zPOYsfAqc=,tag:tpso5aICRmvdqmkFW65XBw==,type:str]
kind: ENC[AES256_GCM,data:lR6EdYYo,iv:BOG17eeggjY5Drriib61QD/oyUZPj7WzR/uG+S63Vbc=,tag:hreVS9WvOpVNLFlR0NcKNg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+5tBVGafnByygO9x,iv:vaDaYnU83sALg8dQ2DzvyCjZ53LmVEtUD3lV0A79mMQ=,tag:FaPQGsCaYg9JxlJ5+ILIGA==,type:str]
    namespace: ENC[AES256_GCM,data:PO7WD2w=,iv:05JBTBPUxiIXKmEE2ysDFGR1cVxiIAJShmzzchJHhAk=,tag:xcrliZFXQICpKtCAa3TEYg==,type:str]
type: ENC[AES256_GCM,data:dvhN6Tk5,iv:Hl4/Fblp3L0M3fbIhqpOfboZQMc8GNPZOJd/1kK3NmI=,tag:khHc8VOFLtlRMOSOUZBP1Q==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:N+1+7dtAulx+H2xnB/hrBH25UdkPzIlPVq53N74a34Fj7sB28yXXWKv2rA==,iv:HO+lM9mhJpMgx+QeBzDt1SkB7gqpcbS2AzCDEvFy0Vc=,tag:0YLif2PFWf17lFJ+U8nZLg==,type:str]
    GARAGE_RPC_SECRET: ENC[AES256_GCM,data:yyXK7PEpJTDfnGSuEdcrMWEyDRooXZ82qZ1JHriu6oiPOw9l08yU/jMmtblrB2k9ixApZe3+k4Q6a00Z+lwxQQ==,iv:ZDx2AOHmcBDgXmsODKaLvfm30iiML69qESD/5ZCwNSM=,tag:fnxO52SYIpBVAgGO45RhNQ==,type:str]
    GARAGE_S3_ACCESS_KEY: ENC[AES256_GCM,data:IABlYhRrD4itmc8vx5XYZGp2sACE7mNY,iv:eeeAt1f8w7Tz9laUpScN3ecurSt14dzW2TQNOHsf5OE=,tag:lZXnt8+0edJrRQsMNUBuxg==,type:str]
    GARAGE_S3_SECRET_KEY: ENC[AES256_GCM,data:dV5NsMR5q7YQW62APztYcVOu8lWbcxcIxOOd1F3JfJcdu8ez4kTQ5vGxyst6CX2M,iv:twjVK2uYMWyN+ee4PhTq2UnDF6DWpsEmpGQjXNz3FKs=,tag:LTQljJe5vLX8PNhmOmT9hg==,type:str]
    LANGFUSE_SECRET_KEY: ENC[AES256_GCM,data:vZzyINQHW6UcGckfibdfMCx2VnAthls69iu4nnQSjQ0=,iv:PnQVJLFPpH0RTRkOd078SiI4EmdHTAjZ7Ztd1XUlzEc=,tag:q7CVcE4R04XRqm0zId59qw==,type:str]
    LANGFUSE_PUBLIC_KEY: ENC[AES256_GCM,data:kwANC3ONeC7TY0sAD048wwn3pgA7pU6qM/At0Aswnug=,iv:ZYRZ7uB5d/BBliA2+qbC50m5Ah5WVyntIUDyHG9EImk=,tag:7P0vfHzBeHYrlHhqVCXWAg==,type:str]
    LANGFUSE_SALT: ENC[AES256_GCM,data:nZEp1l1n530qdCQhU0l93A==,iv:mSVCSGes8PvIEVjNV1Z5YtjjDUeF91m9SPLrgp0Csh4=,tag:P0TLmcxxnKLIN2uKrvsN4w==,type:str]
    LANGFUSE_DB_URL: ENC[AES256_GCM,data:f8PMqaAWOP7RFnUeN+DxVbTry6C/qKWz7vGR0jN5PXiRakZjye+kC00TuoIaGt8CbFJX5Faet+h8X0wa2IljiSX9mVMSk6IcdNZaFFOfGd1nJGxEXzk1FcQlx1+Dam+ymbK9azXaqY9PKfwnvv2wTA==,iv:iUNXq4GnRda+EDbF97dUlhJOYWbA6lY5omH/4hXkClc=,tag:mNdw4AQyHzePq2DGyIYj8Q==,type:str]
    INFISICAL_ENCRYPTION_KEY: ENC[AES256_GCM,data:K1TyXAc8jiu8Aim2a0gkV9a1UTu6g8EeYgD+D+0+Pnk=,iv:RvCCs5548wJnVNt6i34iTTZ01YxR3hZYCe9FyoxUd9A=,tag:kU+z2FwohGDVoewRb2LfiQ==,type:str]
    INFISICAL_AUTH_SECRET: ENC[AES256_GCM,data:rQmy4sN7zQ92l9grWcWpa/cMUSuvg2Sd0ZaqbWZy+Qw=,iv:EUYraxBuls77KTNoHdr6Dhocf0ss92jSlQorNXarkxI=,tag:/HE8xaFFgRmSULJyututrg==,type:str]
    INFISICAL_DB_CONNECTION_URI: ENC[AES256_GCM,data:KHSEf66WQnD/1qlQqoANg9ynO+kuOgr7Rtmomg4fOduXJqMavgJQrmPr/aBIkJ/6UboRSid75B9vzCfFXfMod8eXXUsyX88Pm9kzaYTHu52UHyJcurIxEL/h7FTtAXlO1cTOhn/W2s7iB9dId5XIUHc=,iv:4Y8OwKCZMAyG4fN4bWVbHEmXxH8pJ3t+DxTiiQUCdB4=,tag:afTaXEgX4+S85sMOu0o/Ow==,type:str]
    INFISICAL_POSTGRES_PASSWORD: ENC[AES256_GCM,data:DDAgHvjdByrmTwK0xhJPIBpn1kXQppXgV3elBgvHzzgBa/VAeUqfDxLZrA==,iv:z0yp3VCONg9WAhomrtz5U7vu3DaWJwVTmCzGoqQqZcM=,tag:1vJEZj25wn+/v33kqFC/Xw==,type:str]
    EQUIBLES_DB_PASSWORD: ENC[AES256_GCM,data:jhDH6kGKnOuEm4CJfbXDsg84XWYzpl58n9zw83bJOw==,iv:Zoa6ndt4hmzWHXc8D4r+O+YSfSgoNHGIw+r7DD/V010=,tag:JcwwDBaC3P5UZC21XSmr2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age125amch63h60xmua48jxzjdm4fwr6z387g5zw0mwja4z2533u8f9syye5qr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYXRFeld2NXMzcWhwQ1RK
            YnJhdFpIVC9kS3hsaEhaNWY5MmNmV3JGZVNNClNPbG0vQloxeWRyNGUxT1U0NFhC
            WDFCQWhZNlUvNTNRQTh4MG9pMHRSMm8KLS0tIE9URmloZVZ0dVo4aEpTZzRucjdn
            L0EwR0gxZDNhMkpFYWs3czdlQUw5MWMKD1tUxCBhxcucZncTsI84kc8TkfXZar0L
            hAenyiR+n4aeKHFrDpYF2PjJiOoztcRfKtQoiO9ADiEcvQfIcZotTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T20:02:52Z"
    mac: ENC[AES256_GCM,data:8dXrGChn2L1l+zaMUVzol/s4XEJyg+/y72rsBV+F2R4QbjW1SL+vgptlcQVkHAO2Lbp8TFl3iOakEKAbsXpIu+5z3wuX073yWsuDomjPkYkTxreot+76E5jeuRsEVHEXSS7BzGJhQaxgFfUifSESIo2SknKT6+PWCflY0m7HWOU=,iv:9DIYYpEVsAEy/VdFkqCvJccfJ4ze7lfLoDoQ3dv1snA=,tag:C4dyEs6ouPLH/+zqHBKjGQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
---
apiVersion: ENC[AES256_GCM,data:DEk=,iv:I/i0jBGnHLtzvEdUB5qNRKZV1JBco1oVPVaabr7ksJg=,tag:dcGF3SoAhJ/w8Fz4XZZReg==,type:str]
kind: ENC[AES256_GCM,data:AljMAVrf,iv:5Vt1fCKMj8BYlb5oOK0b+8SWocqnI5rp6WsnLljAUoY=,tag:ythy6+6FJMJQ4AJN0f5BBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7LchOhwCnYqbv7Vq,iv:4jpU6SDP/F/zpgYQ+fuGGTmCd9/badd1UWR/kQ8fAUk=,tag:6sh+NQHGEFOD+X82mj1kNA==,type:str]
    namespace: ENC[AES256_GCM,data:jFvl,iv:TNjpULMe6gI2cfBPwrPanv0rd9jZ0getqP9lz8lAmPk=,tag:wZzVNbR/sxSQ47ghorm44Q==,type:str]
type: ENC[AES256_GCM,data:yeIJaWY4,iv:cohlmI48b4i5fk/FM/FI9Vk//B0HDih5SCpZ/DFD9Ic=,tag:MTv1MFPKBKPf/JcjUzShHg==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:IafZqx7TOUG2V3EFPmZNwAUw3viLsYlVVDk/+zCoFtc2lDpPv5CQFLWM+g==,iv:+sn+Ugobpj8yNEZawaI7pcKkHGq8MWoyrmmHo4o4qRk=,tag:nhZHPcKrto0mlvKIM0upaA==,type:str]
    EQUIBLES_DB_PASSWORD: ENC[AES256_GCM,data:5uZB/QAybRbSrZquEQZatPUSRTESKGX7xFHQHXcxTw==,iv:tB6TA8zXnL5jlf7LcpNJvTDDLrO368n454mBvh7YZV0=,tag:7XmBUXCgm6IWVWuK1c0s3Q==,type:str]
    EQUIBLES_CONNECTION_STRING: ENC[AES256_GCM,data:i03qken5y9TtpV2s5ow4VNprmSYAgkfeJsT0P9QeLQZBnsuTVke+JbEQSnznWxIvXQrKtCd9xcD+i68A9vasMCc5ClOdv4Z+F3+8nlQ386qioEyR1Up3Eqc/HOP5edrOVFIA49c8urjBT1+Mt/LH2w==,iv:K2fTCcCgWiFiJjdCXA+Wo9SjN1W7dP3m22pot2lKgDo=,tag:DHU73dYDHbT4ht9Pi3GbgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age125amch63h60xmua48jxzjdm4fwr6z387g5zw0mwja4z2533u8f9syye5qr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYXRFeld2NXMzcWhwQ1RK
            YnJhdFpIVC9kS3hsaEhaNWY5MmNmV3JGZVNNClNPbG0vQloxeWRyNGUxT1U0NFhC
            WDFCQWhZNlUvNTNRQTh4MG9pMHRSMm8KLS0tIE9URmloZVZ0dVo4aEpTZzRucjdn
            L0EwR0gxZDNhMkpFYWs3czdlQUw5MWMKD1tUxCBhxcucZncTsI84kc8TkfXZar0L
            hAenyiR+n4aeKHFrDpYF2PjJiOoztcRfKtQoiO9ADiEcvQfIcZotTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T20:02:52Z"
    mac: ENC[AES256_GCM,data:8dXrGChn2L1l+zaMUVzol/s4XEJyg+/y72rsBV+F2R4QbjW1SL+vgptlcQVkHAO2Lbp8TFl3iOakEKAbsXpIu+5z3wuX073yWsuDomjPkYkTxreot+76E5jeuRsEVHEXSS7BzGJhQaxgFfUifSESIo2SknKT6+PWCflY0m7HWOU=,iv:9DIYYpEVsAEy/VdFkqCvJccfJ4ze7lfLoDoQ3dv1snA=,tag:C4dyEs6ouPLH/+zqHBKjGQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
---
apiVersion: ENC[AES256_GCM,data:8WU=,iv:7EI9xiFGhA+s+5Gy5Ug/6+Xibp+oqnooyD+gTtoGc+M=,tag:KKimPqyNH2JPSDpWouTjKg==,type:str]
kind: ENC[AES256_GCM,data:pUKnsSVU,iv:S48NyopMnT6gWPDJputmfZIMBuzcBe87Ksaq12Zz0aw=,tag:6ZRETtfp93xy4J8GTspFWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:r0o11Ow/q4N6m64w,iv:TKl+U8o4eNkVnxvyE10HJVJ6HqyBqkMiIixydwVvNHo=,tag:WAigix/F2+efezJw1v+72w==,type:str]
    namespace: ENC[AES256_GCM,data:4ruSjS1dIrvOS+I=,iv:W1RTyO8r/bs8HJ3wLp2spMa6BEXfRKrhyXQvK08Tqpk=,tag:rN7PbmDQ/tT7/28st4jI+w==,type:str]
type: ENC[AES256_GCM,data:gqEinKOC,iv:4B2A3xMSB5QhyctwnMAoOYAdEuD1Ah7clUAPUBxlSck=,tag:LmOdUWSLnwD1dE0yvPlytA==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:JhhY2Bc7Yg/V7GQSO+Ni15AICO8OX7wVVdp4Z2buJYXYe3b6Oj3YQiMLVQ==,iv:ZtlsFmJ0fFY5lLdDbC9+K0cPGX62yCDYZ2vujEviQX4=,tag:qZ827XDbO0DyNItqRtGjmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age125amch63h60xmua48jxzjdm4fwr6z387g5zw0mwja4z2533u8f9syye5qr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYXRFeld2NXMzcWhwQ1RK
            YnJhdFpIVC9kS3hsaEhaNWY5MmNmV3JGZVNNClNPbG0vQloxeWRyNGUxT1U0NFhC
            WDFCQWhZNlUvNTNRQTh4MG9pMHRSMm8KLS0tIE9URmloZVZ0dVo4aEpTZzRucjdn
            L0EwR0gxZDNhMkpFYWs3czdlQUw5MWMKD1tUxCBhxcucZncTsI84kc8TkfXZar0L
            hAenyiR+n4aeKHFrDpYF2PjJiOoztcRfKtQoiO9ADiEcvQfIcZotTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T20:02:52Z"
    mac: ENC[AES256_GCM,data:8dXrGChn2L1l+zaMUVzol/s4XEJyg+/y72rsBV+F2R4QbjW1SL+vgptlcQVkHAO2Lbp8TFl3iOakEKAbsXpIu+5z3wuX073yWsuDomjPkYkTxreot+76E5jeuRsEVHEXSS7BzGJhQaxgFfUifSESIo2SknKT6+PWCflY0m7HWOU=,iv:9DIYYpEVsAEy/VdFkqCvJccfJ4ze7lfLoDoQ3dv1snA=,tag:C4dyEs6ouPLH/+zqHBKjGQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
---
apiVersion: ENC[AES256_GCM,data:0oA=,iv:fgID8U7sjdI2q6cBxhBu647J4LIpOXrFiA9wPFU1bZE=,tag:CRHJTrnCl4OuM/s2p+H1ig==,type:str]
kind: ENC[AES256_GCM,data:yNx2xlge,iv:C5BcFkr8kdFWDfwKaCAdckWkTkbBiqnSZLSUlfSHifI=,tag:+KSVDH0QPR1v9sv2TKamLQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VwgbgPgoegp3aD5L,iv:fAbiEB6ILOq2qgjrW6IpghFghGtcWWDib+6BVihMe7g=,tag:GiWYQpuxNKaV+PKTb2Uwfg==,type:str]
    namespace: ENC[AES256_GCM,data:a0HN,iv:QOjewm3UI3jLGDWZ4Q5bmO/zNGCaE7k7HtpXZ6JuM5E=,tag:Bz2di7reXr/fVbREBP6Xjg==,type:str]
type: ENC[AES256_GCM,data:qmwcHlJT,iv:pNs+9PWfLU4sVVZMASRt13BRa30IfUwCYSRswBm+VO8=,tag:KvdVpfDU+mPmj0f5ycG7TA==,type:str]
stringData:
    GITEA_ADMIN_PASSWORD: ENC[AES256_GCM,data:G94vzm3Pf9V51qRxVH2jWiABpUA8OFetXBWFjiYWdUB//UL+6wjaoSKfl4z/xes8330+fA==,iv:vVu2SChrK3HOKzYU4MFNnzbma1xBjDLH7s8uSkF70ps=,tag:PMzdvKKo1jUVuU5htn6dow==,type:str]
    username: ENC[AES256_GCM,data:qFk6U44=,iv:jbLZ9bDZeO8c6+lnEg0wadb6sLDJg4NZRrVD3O6FdVo=,tag:orUTB0fBScf1tOTJhu8UGQ==,type:str]
    email: ENC[AES256_GCM,data:ZjxORtqeoLl5xd8e6Ow40e3ui4xR,iv:Z4J2wjIcx5OQdR7uJDmWj9eC4N56FrKLjgC8c8BYLss=,tag:uxRc6+2d6059awv8G1Hbtg==,type:str]
    password: ENC[AES256_GCM,data:hsyXWKcGRdR5OfoP0ytlfO6YOH35Xuboy7gT5+UTOxIATRb7W2YZ+AfGo/BlvdBWpK7HjQ==,iv:qb8nqJoKAxsxKJULgv6If30MF+mzqJLRvmQo4xBQM0c=,tag:BFdfSDSDV8SHO+qm22RAvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age125amch63h60xmua48jxzjdm4fwr6z387g5zw0mwja4z2533u8f9syye5qr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYXRFeld2NXMzcWhwQ1RK
            YnJhdFpIVC9kS3hsaEhaNWY5MmNmV3JGZVNNClNPbG0vQloxeWRyNGUxT1U0NFhC
            WDFCQWhZNlUvNTNRQTh4MG9pMHRSMm8KLS0tIE9URmloZVZ0dVo4aEpTZzRucjdn
            L0EwR0gxZDNhMkpFYWs3czdlQUw5MWMKD1tUxCBhxcucZncTsI84kc8TkfXZar0L
            hAenyiR+n4aeKHFrDpYF2PjJiOoztcRfKtQoiO9ADiEcvQfIcZotTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T20:02:52Z"
    mac: ENC[AES256_GCM,data:8dXrGChn2L1l+zaMUVzol/s4XEJyg+/y72rsBV+F2R4QbjW1SL+vgptlcQVkHAO2Lbp8TFl3iOakEKAbsXpIu+5z3wuX073yWsuDomjPkYkTxreot+76E5jeuRsEVHEXSS7BzGJhQaxgFfUifSESIo2SknKT6+PWCflY0m7HWOU=,iv:9DIYYpEVsAEy/VdFkqCvJccfJ4ze7lfLoDoQ3dv1snA=,tag:C4dyEs6ouPLH/+zqHBKjGQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
