#ENC[AES256_GCM,data:Awd21dKC2s3qnFZToG3me4Eef4LvW0yOCEYjcamVhhXfzFd77vu0,iv:t7vCLo3aJdN7JHyjZ8HpOk1MrU391n2Kmw6DEpSU+z0=,tag:1S1tO/+e3BP75zwtD+oJsA==,type:comment]
#
#ENC[AES256_GCM,data:93DOszssOXVpbjFynnrtCW++vAVH9kOPuUj8v4s+8to+cJzzCvM=,iv:/8DZm3wJGdZC/kuuJmfDCIlb3kDFYIX/8LfH2Pts26c=,tag:HR4V9KabWpatlg2kX1vxtA==,type:comment]
#ENC[AES256_GCM,data:tFowEz+GA0awQJC6Iok61BoF9YMrzw6tXVDobWH2vdClOAzVDyQGd2zqY1XMf0jvNQ9DwN0k0p7qcseFLuQCZY+8WtPa,iv:/ptspqVDx6bUL1bTk2dcoPoY5GK4nJmzgK2wMCAQgaA=,tag:Cm3CX0MfuzSQLDfhhWInFg==,type:comment]
#ENC[AES256_GCM,data:1SLmj1KUzellD99ZA/1x9KUSzzfC8UIO3IZXmMRWleT6nNiJM3VuZct23T/e7UnYfw==,iv:gqxJtlTFX0PVc0UiBDCZXx2WAZrZ55p76oQmt7zUAmw=,tag:1KML5S+yPXiZWjMyQ6sd/w==,type:comment]
#ENC[AES256_GCM,data:jFCaYbIcKeiXNDibmP5YAdodLpzHSM5rq2K6f8F6kBsYELW9KCnnIFEYjA==,iv:svgwMZ0IZ4/5u6rcOPwwqN1IDaA4Dh7rWPoPDoVwLpI=,tag:C90IzS71vjs/6AtbAhfasQ==,type:comment]
#ENC[AES256_GCM,data:YOo7TYhHGv0N/g10Vw1x/rgrfRsIa20Fhm/bbydMQ0Q146pmg3NRFuOxu1cmZ7hcDRPeeJMbX3k=,iv:ObCrbdqC72bU9CG7fj5RVP4Apv2cd3TZ6bJq8KQwqtU=,tag:ngCFGLO1QNpsHkS3LhYWhQ==,type:comment]
#
#ENC[AES256_GCM,data:LF9ZITCMDWl8Kl8efkxkijKAxDr3aAaBpM2J/JRictByIP6IPfACjmZH79oGkItE/QWRBFv0flW92fo8,iv:b9jDewvibrfeEiUiDqAwqhp5SFCA5ClwKqMxLHhr64Y=,tag:/iM5pHONvkOp3fXt5Aw2+g==,type:comment]
#ENC[AES256_GCM,data:hX1zSY8jgw2gk5EpmLK10Z3TNWLucjCVW24/zzJpjIb332v8VHQpPJAu+hwMKNuDJYi7Rfyl0zZqZV2kmlMT9CNocsZVSkgKxH0=,iv:e9PumqHAzwTU7powxQvUAHbXeUDmt6ParVYlYy0hKQw=,tag:B52xLmvxnW8iDpOmJy8mcQ==,type:comment]
#
#ENC[AES256_GCM,data:0ZNFYoyu+0fD5Bs4jUHbyDTOYWzPV70ppI23evTJbMiWlyoDcjObJK3ITUqh4069ZYrETQbx/8TZ4uSArRQYWZs=,iv:ZuJ3L6iJ2PHSip4//X3289x4y+r60ncdUDZ1RU1s4VI=,tag:5Oi0dz9hXTfXnIT4GNKCCw==,type:comment]
apiVersion: ENC[AES256_GCM,data:kbA=,iv:t8H81v8QP0cm6gQuPRJ3IFpbhiNxIVZbgf2blmn517o=,tag:9HHcbCSTQ4UQi4vx4z1SmQ==,type:str]
kind: ENC[AES256_GCM,data:fJ6+C9la,iv:gZqeaiVCRbLszO/oBFvzPBFtOa/MFxXaMRpCmIrBMjc=,tag:oyicRhwKcCeLlv0S3Tk8Sg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wM0sUSpGfY2XuVUh,iv:YTYT37WZxKp3XtpLTLYALrfibW5761u+A2PaBQz9QVY=,tag:xHsqM+9fdyFuImqCD2Xw1w==,type:str]
    namespace: ENC[AES256_GCM,data:wa+zmGc=,iv:C4UWwPztNFfTlffDs6W5DLm5BgtK3PZ8D/cn/hh7NfE=,tag:ZYr7Hf0crpompSAVbcNMyA==,type:str]
type: ENC[AES256_GCM,data:WW8rthWh,iv:xrM1dECfEKOPAVPvz2+RpoRfd6tV6NjCmlhu/XS+MAw=,tag:E34F72613wIL3UwtcWOpLA==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:7+AqXA5Ull3wKwvLQltAPGw//BCRB0IjoqlXsN+lygG+jAQripKKNuZEUA==,iv:rslk8X/2ae5hI6JbJuQRwHbZ8W+tlqWDoS29frXpUi8=,tag:wiXDm8PbUOc8/gnAtFVNvA==,type:str]
    GARAGE_RPC_SECRET: ENC[AES256_GCM,data:6YEK7/xF7YVCFglHex6UZs3wmUz48ivfDU1MilXRK4joInRGgwIKXM5SHPb3+iASJfhz571LLYJXsyzwwYagkA==,iv:5EkEpUcMH85X2ELXXjxKX3CK+6JtjrSr+wpVH5V8LB0=,tag:sCK1ElcdGligPm55V6flQw==,type:str]
    GARAGE_S3_ACCESS_KEY: ENC[AES256_GCM,data:LivkOX8XWQzsFM4Ay5fAybF5ZnbMZimh,iv:/qTmcAVfqBeC7bLNWJ8rwc2boFJZElcBilfpvUWHv1Y=,tag:3yPSGdBJ+becDWrH0iF+/g==,type:str]
    GARAGE_S3_SECRET_KEY: ENC[AES256_GCM,data:SbvGWjqaz9Rz5DgAl+2B6BAr6+1WwrT1IioiWenKu04IVrbNLVlWiG7rZGkvO+8P,iv:1nVPj34rfmJ8xTesiVwaK95JKXNUkN1mcHKphWhcTFY=,tag:1KhzHUdeT+7P2GqCFqJKtA==,type:str]
    LANGFUSE_SECRET_KEY: ENC[AES256_GCM,data:DZpk+vzhIBTlwr/Sm5qZ0mXV5+1MJKhJcyr0OuqqZ2s=,iv:OMGau109jwHpBVcE5KNqf5SNSojJ2xhlDojtGmrhehk=,tag:xbn04hP1Ol86eUBqy5MYXA==,type:str]
    LANGFUSE_PUBLIC_KEY: ENC[AES256_GCM,data:/8YrPs1X5fHcixwSqFwEeMl7BgVNSiPfaqZ7fdiCy+A=,iv:K1ANp+pfok4J2JMQAEIVP4HxGZZmt2YolbOMJx55z44=,tag:1hxAU/i4YI5tYinmdoLCMA==,type:str]
    LANGFUSE_SALT: ENC[AES256_GCM,data:to2zli4wW6N6nrnSLkrVNQ==,iv:vtsmT8StlXIaMo0EuYOx0lwjBczPcSKAP6EI/XaFKKg=,tag:/s36N4a+vNOcYKJRA9lVZA==,type:str]
    LANGFUSE_DB_URL: ENC[AES256_GCM,data:9HJeq91TBs3XNLuzWsr9Ew89Dnu7900ntkREfUA1lbnsO+R0EZbSXLS9bXyGUILHnyayr/10YqloYOEz5DlW98LqfIKW+8A/cNvSrl1wTmP7rIqTASGKl7fCa/yBSM8GjzbhbSMeytrbU+B0SzCfkQ==,iv:a/zf7roJF2Vo791d/yuYbN/3M6H8qv5ItlQzEGoSDXY=,tag:aPx752t3oVAsEMXLIkwoLw==,type:str]
    INFISICAL_ENCRYPTION_KEY: ENC[AES256_GCM,data:Hr/jxoiiSLScBO3/3l4w92XyYi4YRAGgzFpzZof8iGs=,iv:rXmmLRDNsSHoB+QQ/QS1ecqsbhAArZMBZxgEpW9Iqvo=,tag:YeikBeD0WhScoweInbXrcQ==,type:str]
    INFISICAL_AUTH_SECRET: ENC[AES256_GCM,data:1v0uKKGoH/Ml1MZlkM+LkSal7TRg1a6+GhWsOX5xFVM=,iv:enJT9BMQKpUTGPbZFUjNm5f7BoSHlfWiPkA3mBW127w=,tag:MLLSyZjMXIclmyRjDTNXSg==,type:str]
    INFISICAL_DB_CONNECTION_URI: ENC[AES256_GCM,data:Esi2pbe2x7KtKLXw26dyHwzEml0suCP3MtZbOitKR2AttqW0WjydpCLEiQVWVjPaAOsBZ5gkmMa1WXwtAx768b3tzLX07JKhjWaroB0f4awBON8OrWqaKgv9arx2qa4EzxUy0Z4vucRQxzsRffXVC0k=,iv:XAme+FEsK03wJgyxuOBDLNeOZuAoQMQOeXDPEcFyb1I=,tag:s5yRCERetCnF2yOdmx9Tpw==,type:str]
    INFISICAL_POSTGRES_PASSWORD: ENC[AES256_GCM,data:9G+I9p6wap52Id3rAZcwOO2r5XkXDBeORrg0DJnnxXllMIUhOibLEA/Gpg==,iv:c+HptxpZV6fiybtFjreWZIj3eMcucEj/w8DtsrEwnQk=,tag:SUW+/jFR75QDwimLekBDkg==,type:str]
    EQUIBLES_DB_PASSWORD: ENC[AES256_GCM,data:WH4aOkX0ijEr5l5d1/SgGPQubrqGq4nTXonfjU8/qg==,iv:VEDPXCLYAYMakXtpcWD87Pj27gP9FhB/eQYSt7O8vSQ=,tag:yR38ggLsUTftC7xoNwRuAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age125amch63h60xmua48jxzjdm4fwr6z387g5zw0mwja4z2533u8f9syye5qr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSnZSNG1CVGFPbHh6NXEv
            S2E0elVHNVU1RWdzR1Q4QkpIbEUvME84dFVnCnR2QkhQQ2k0Qm1kY2VRSG12emFL
            ZjlSNkJHUzNvZWptSHlhYWJwNm5tVWcKLS0tIFp5QnQ5TnpNQnhPc1VqTktqdjN1
            dFdQWGZwTHVIdEdQSGVWcHVtZEI1VXcKZSprnYevdYJOFr4ShQeDHWWIudSGYmIK
            XgiGtx0ECv6ZYezlm2Bq0+uEnoWrd1DnIylCF9YsLQ7WipFjV/4HiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T20:05:30Z"
    mac: ENC[AES256_GCM,data:YtGSvr5ktAEazC7QiT80nyu9XzQuvU83+6noe59+FV+ztq3B4YE/3h/7vJPYpQZ+vlh/hiVuyR7w3DED2nuC7MzcRlL1S6raEuiA7LzATdMvYrMJKYqH8HqxfP4rlODa0XgGZiebqe42BO/d9LHunGeD9JGOQAfpJr5INVWBMX4=,iv:XjtW4opohe8aFOTN2pNc5a/HHO2hyFRXAoHvm6TOgrw=,tag:rYkLBGa0sDTpjSWB6Xhq6Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
---
apiVersion: ENC[AES256_GCM,data:LBw=,iv:gVFjaJyBEiboLDfIpTq+rQC3Qxg3aCWFKuJDMLuGMBM=,tag:RbA+DQtmcgiNhrPFfm/YrQ==,type:str]
kind: ENC[AES256_GCM,data:jAl0IU8s,iv:U3pkF2I7hqSSg6J94/K57XpqIpYJW1FkmU8qnOwK02s=,tag:hUicjoeci+XAiWQLluZVMg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:akEJSM//o0sxOJmQ,iv:lDp5onIt79FOt5mm2kI8+JrubNdpB0oYbkuiNY+jGr8=,tag:zBwNlWq4fUtIO3uqXV3RlQ==,type:str]
    namespace: ENC[AES256_GCM,data:pvdS,iv:ilUH/riPACs9h9NU8lcB1LEiJWU1PJpfhEWaxFTs0RU=,tag:3Hw4qOU3yVJrNl9VqgupqA==,type:str]
type: ENC[AES256_GCM,data:ru1/c79e,iv:wF2yAM4YGCfcRPgo6Z7ROp1tjxgteSX9Cv6lamoKb7w=,tag:d1oAjCn+4m7Is5RIVdWVNA==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:7NHLKDzTj7esmmEFr+ZePGh1WSj9ZLJw1cZUCOY3Z6WSSY5vRfy52BilCA==,iv:nwtDKD1KNHf/A4XU6SDFSjpaOrBNB5nS0KHjO3ZJeXw=,tag:AxSjy/PJKwavjruwSzFczg==,type:str]
    EQUIBLES_DB_PASSWORD: ENC[AES256_GCM,data:vUdiK8aYVRvK2BSsUNk/lx7f0/gBl8BWt/TDSLLekg==,iv:56beWytdcKS0cZ+QV1BJC7hb8JTKckad+/+9/I13ZWI=,tag:sYmnOObTZ0Q+jWk3v+cAxQ==,type:str]
    EQUIBLES_CONNECTION_STRING: ENC[AES256_GCM,data:9Y8hSBwLR7rayp6xJSeWG18K11/arPPApqBgR74R6eHMq1jbyUuDi72FYXbhUYsmx+2QRdid5rjo7rWQsFy9x2axg+S7gqhUGwpnYfA62lzqYkI94nBQ34xsjS+yGmCXV256BJptGqpTe++h3g/oKQ==,iv:bMeYgHuW2siKhtjl6Iqnkf3HtXTUroz0ww/6rSRD+DI=,tag:+/O9ZNE6UIUbSnBkriCxTw==,type:str]
    SEC_CONTACT_EMAIL: ENC[AES256_GCM,data:n5kFe5PQY78okMT6W9vL5Ha2VdQ=,iv:gUpLN2G4s4wBn6HhgWdAep45uVIzIIKLfYb/hdN2nZs=,tag:2GC+bTLtukV+/Ze3T8gcLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age125amch63h60xmua48jxzjdm4fwr6z387g5zw0mwja4z2533u8f9syye5qr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSnZSNG1CVGFPbHh6NXEv
            S2E0elVHNVU1RWdzR1Q4QkpIbEUvME84dFVnCnR2QkhQQ2k0Qm1kY2VRSG12emFL
            ZjlSNkJHUzNvZWptSHlhYWJwNm5tVWcKLS0tIFp5QnQ5TnpNQnhPc1VqTktqdjN1
            dFdQWGZwTHVIdEdQSGVWcHVtZEI1VXcKZSprnYevdYJOFr4ShQeDHWWIudSGYmIK
            XgiGtx0ECv6ZYezlm2Bq0+uEnoWrd1DnIylCF9YsLQ7WipFjV/4HiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T20:05:30Z"
    mac: ENC[AES256_GCM,data:YtGSvr5ktAEazC7QiT80nyu9XzQuvU83+6noe59+FV+ztq3B4YE/3h/7vJPYpQZ+vlh/hiVuyR7w3DED2nuC7MzcRlL1S6raEuiA7LzATdMvYrMJKYqH8HqxfP4rlODa0XgGZiebqe42BO/d9LHunGeD9JGOQAfpJr5INVWBMX4=,iv:XjtW4opohe8aFOTN2pNc5a/HHO2hyFRXAoHvm6TOgrw=,tag:rYkLBGa0sDTpjSWB6Xhq6Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
---
apiVersion: ENC[AES256_GCM,data:Wh0=,iv:az6uksDootWBlTCymGSBkIM9ATpHKTPqi+Ovmn+WZxM=,tag:S6La+X8TDVtjS8Ug0fRDrA==,type:str]
kind: ENC[AES256_GCM,data:SsVTbAsD,iv:TZwqJRpzuVxfYLVxMZHBRGJ9vrDpJ24W+njqfUbGdG0=,tag:A5JiRs7BhehB89bXtJTMiQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:00rKXUBillqH2bPj,iv:Jc84d/VqphEpadZfGe7YruDQP50Zf8OKLI4V+OlF6NU=,tag:pAHnPW09CfsPw4yDt00uLw==,type:str]
    namespace: ENC[AES256_GCM,data:fs3TRloSbwxmpHA=,iv:xiKiq2TfeHh2Cnbj/KVogqb3t/d62WB4aQqzAryPXjA=,tag:QicRA33DybtxASHt5xWJYQ==,type:str]
type: ENC[AES256_GCM,data:JYCg6rjQ,iv:UIinXFni5gRQTfj5jEyz+J3Ev0p54NgiU5VSkv9sdkE=,tag:aknPk/tKZkVRF7LwW3384Q==,type:str]
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tO6mW2/WsWf4oh9kXrryEuT5DN0abEI4njsFBMJwUEZ/QQNL/OCrSQZMrQ==,iv:X+V+qnaQrupYVFJjsvE/Fxm7KNngYWqghTHm9wjlvA8=,tag:KQfWCVpTB5xqcJ3XqoxnuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age125amch63h60xmua48jxzjdm4fwr6z387g5zw0mwja4z2533u8f9syye5qr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSnZSNG1CVGFPbHh6NXEv
            S2E0elVHNVU1RWdzR1Q4QkpIbEUvME84dFVnCnR2QkhQQ2k0Qm1kY2VRSG12emFL
            ZjlSNkJHUzNvZWptSHlhYWJwNm5tVWcKLS0tIFp5QnQ5TnpNQnhPc1VqTktqdjN1
            dFdQWGZwTHVIdEdQSGVWcHVtZEI1VXcKZSprnYevdYJOFr4ShQeDHWWIudSGYmIK
            XgiGtx0ECv6ZYezlm2Bq0+uEnoWrd1DnIylCF9YsLQ7WipFjV/4HiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T20:05:30Z"
    mac: ENC[AES256_GCM,data:YtGSvr5ktAEazC7QiT80nyu9XzQuvU83+6noe59+FV+ztq3B4YE/3h/7vJPYpQZ+vlh/hiVuyR7w3DED2nuC7MzcRlL1S6raEuiA7LzATdMvYrMJKYqH8HqxfP4rlODa0XgGZiebqe42BO/d9LHunGeD9JGOQAfpJr5INVWBMX4=,iv:XjtW4opohe8aFOTN2pNc5a/HHO2hyFRXAoHvm6TOgrw=,tag:rYkLBGa0sDTpjSWB6Xhq6Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
---
apiVersion: ENC[AES256_GCM,data:Ssk=,iv:F/FXw1R9Ha3bx/hfdf5BLY5sMWThRlEU0RK2Mg2Au+Y=,tag:gQaMMPLSGlKsR3VqILWcwg==,type:str]
kind: ENC[AES256_GCM,data:B3uYEuKO,iv:ITp9oE2gwgwLDqTMA/LIZ33He8seirrIpgZ/eif3zBY=,tag:ZIJD4Ut6U8Fg9Rp+XX5E9Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YQGUzl+fGJzjZlM7,iv:JyQLW+pRpefm7UOyb07YVUx1w68eG3gN+dDLqP3UlAc=,tag:RrPbBDYj9I2PYLB4ArDLfQ==,type:str]
    namespace: ENC[AES256_GCM,data:wOiU,iv:w/IbK/2tqiFrCTAQSvBinICE2MAJ3KdaoJLTfS+w41I=,tag:5d5lpE/DKj+2yS9LQxjUkA==,type:str]
type: ENC[AES256_GCM,data:Y9jhhHzL,iv:FW1ZuHVxJUIQLpVI6+4aqRHKYMN50Z7CbhwdU3H9zkQ=,tag:Ai9waOrvCtNLo6UEJY1tIg==,type:str]
stringData:
    GITEA_ADMIN_PASSWORD: ENC[AES256_GCM,data:yOkAqofEtXVpAsC4c3+xCC0C+uMIPUUCneQjjvF5rwu58yRKvX5dJmzOZSEl6X2PZ27s/A==,iv:vC/UdKBMt7F+fIvxyHPQ4lbOpW3O1h9clLXiTXvG8Qo=,tag:vbjWknGFufDnAoDLiQIZjQ==,type:str]
    username: ENC[AES256_GCM,data:hPXpn/0=,iv:94yA38FzTR9U3RvIHjQbfZrNTNOsHRZPZnuosg62cxA=,tag:aZlb2qj3Twedn/wCh/MHtA==,type:str]
    email: ENC[AES256_GCM,data:BgCMIMaTmlkjiRAwb4YDhbL9KWAG,iv:psDj/9M2Vza4dCcJPxwi1pjB1meHfPToUB9s4GDZicY=,tag:IQ1dk1pm1vRNYlIyTj6OWg==,type:str]
    password: ENC[AES256_GCM,data:a8UDnW0sqHSshL+jMqoUPP+5dNXx+ZuMSB2FyXzxXSnuFrzrQQDpaA3ot+P/NjnRQX8hnw==,iv:z5SnSCbLG4GsCe/lK0X2A5qXPHFAlanEaASIRD3E+FU=,tag:TCT7nAvlq1kPI7K6CNBI7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age125amch63h60xmua48jxzjdm4fwr6z387g5zw0mwja4z2533u8f9syye5qr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSnZSNG1CVGFPbHh6NXEv
            S2E0elVHNVU1RWdzR1Q4QkpIbEUvME84dFVnCnR2QkhQQ2k0Qm1kY2VRSG12emFL
            ZjlSNkJHUzNvZWptSHlhYWJwNm5tVWcKLS0tIFp5QnQ5TnpNQnhPc1VqTktqdjN1
            dFdQWGZwTHVIdEdQSGVWcHVtZEI1VXcKZSprnYevdYJOFr4ShQeDHWWIudSGYmIK
            XgiGtx0ECv6ZYezlm2Bq0+uEnoWrd1DnIylCF9YsLQ7WipFjV/4HiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T20:05:30Z"
    mac: ENC[AES256_GCM,data:YtGSvr5ktAEazC7QiT80nyu9XzQuvU83+6noe59+FV+ztq3B4YE/3h/7vJPYpQZ+vlh/hiVuyR7w3DED2nuC7MzcRlL1S6raEuiA7LzATdMvYrMJKYqH8HqxfP4rlODa0XgGZiebqe42BO/d9LHunGeD9JGOQAfpJr5INVWBMX4=,iv:XjtW4opohe8aFOTN2pNc5a/HHO2hyFRXAoHvm6TOgrw=,tag:rYkLBGa0sDTpjSWB6Xhq6Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
