apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - garage.yaml
  - forge-registry.yaml
  - victoriametrics.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml
  - loki.yaml
  - vector.yaml
  - grafana.yaml
  - grafana-dashboards.yaml
  - infisical.yaml
  - langfuse.yaml
  - overflow-gateway.yaml
