apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forge-registry
  namespace: infra
spec:
  interval: 5m
  chart:
    spec:
      chart: ./infra/charts/forge-registry
      sourceRef:
        kind: GitRepository
        name: tech-noir
        namespace: flux-system
  values:
    image:
      repository: registry
      tag: "2"
    persistence:
      size: 20Gi
      storageClass: local-path
    service:
      type: NodePort
      port: 5000
      nodePort: 30500
