{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: overflow-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- range $k, $v := .Values.serviceMonitor.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      app: overflow-gateway
{{- end }}
